name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      
      - name: Autenticação do Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v6.5.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            gabrielsantos-cloud/kube-news:v1
